services:
  db:
    image: postgres:15
    container_name: container_name
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    networks:
      - pizzeria-network

networks:
  pizzeria-network:
    driver: bridge